version: '3.8'
services:
  mysql:
    image: mysql:8.0.21
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  node:
    image: node:14.8.0
    working_dir: /home/node/app
    volumes:
      - ./gate-simulator:/home/node/app
    command: 'npm start'
    ports:
      - '9999:9999'

  openjdk:
    image: openjdk:11.0.7
    working_dir: /usr/src/myapp
    volumes:
      - ./artifacts/aqa-shop-mysql:/usr/src/myapp
    command: 'java -jar aqa-shop.jar'
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - mysql
      - node